### ISSUE TITLE
Permission Denied error when building tags on Windows

### ISSUE THREAD

**Issue by syvsto** [dan-t/rusty-tags#49]
Hello,

I'm trying to build tags on Windows 10, but it fails with this output: 

```
Using configuration: vi_tags='rusty-tags.vi', emacs_tags='rusty-tags.emacs', ctags_exe='None', ctags_options=''
Found ctags executable: UniversalCtags("ctags")
Fetching source and metadata ...
Creating tags for the standard library ...

Creating tags ...
   for source:
      C:\Users\s\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\src\rust\src\liballoc
      C:\Users\s\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\src\rust\src\libbacktrace
      C:\Users\s\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\src\rust\src\libcore
      C:\Users\s\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\src\rust\src\libstd
      C:\Users\s\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\src\rust\src\libterm

   cached at:
      C:\Users\s\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\src\rust\src\.tmp2UQ9VR
ctags: cannot open tag file : Permission denied
```

This happens both when run as an administrator and otherwise. According to other people's output, the cached into a file named rusty-tags.emacs (since I'm building Emacs tags, though the issue happens for Vi tags as well). I tried creating one, but the error persists. No file starting with .tmp is found in the directory either. 

Building tags from CTags itself works fine, though I would love to have the convenience of rusty-tags to handle the standard library etc.

**Comment by dan-t** [comment]
Hi,

it looks like the `ctags` executable has no write permissions for the directoy listed under `cached at`.
Are you able to create a file in this directory.

Greetings,
Daniel

**Comment by syvsto** [comment]
Yes, I can create files there. I can also run just ctags, without rusty-tags, in the directory, and it returns a TAGS file that looks correct. I also attempted to run rusty-tags on my project from inside WSL, which worked (though the resulting file is unusable since all the paths are listed as Unix paths).

**Comment by dan-t** [comment]
That's strange. I don't know what kind of Win10 specific file permission settings might be involved here, why calling `ctags` from `rusty-tags` should behave differently than calling `ctags` directly.

Could you delete the envvar `RUST_SRC_PATH`, to see if you get the same issue for other source directories.

Could you also test if can call `ctags` with the same output file as listed under `cached at`.

**Comment by syvsto** [comment]
When running without the RUST_SRC_PATH set, the program runs for a while, printing a lot of these types of messages:
```
Found package of 'serde_derive'
Unsupported target kind for dependency: proc-macro
```

I guess those are to be expected. Then:

```
Creating tags for 'server' ...

Creating tags ...
for source:
C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\fuchsia-zircon-sys-0.3.3\src

cached at:
C:\Users\s\AppData\Local\Temp\.tmpeSnY62

Creating tags ...
for source:
C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\cfg-if-0.1.5\src

cached at:
C:\Users\s\AppData\Local\Temp\.tmphm7zIv

Creating tags ...
for source:
C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\bitflags-1.0.4\src

cached at:
C:\Users\s\AppData\Local\Temp\.tmpYAuubD

Creating tags ...
for source:
C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\bitflags-1.0.4\src

cached at:
C:\Users\s\AppData\Local\Temp\.tmpWaP4OF
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Message("ctags: cannot open tag file : Permission denied\r\n")', libcore\result.rs:1009:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Message("ctags: cannot open tag file : Permission denied\r\n")', libcore\result.rs:1009:5thread '
<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Message("ctags: cannot open tag file : Permission denied\r\n")', libcore\result.rs:1009:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Message("ctags: cannot open tag file : Permission denied\r\n")', libcore\result.rs:1009:5
thread 'main' panicked at 'Thread pool worker panicked', C:\Users\s\.cargo\registry\src\github.com-1ecc6299db9ec823\scoped_threadpool-0.1.9\src\lib.rs:236:13
```

Running CTags with the output file set to the one in the top comment works (for reference, this is the command run: `ctags -f C:\Users\s\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\src\rust\src\.tmp2UQ9VR --recurse=yes C:\Users\s\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\lib\rustlib\src\rust\src\*`).

I also tried disabling write protection on the folder to the standard library, but it seems Windows doesn't let you do that any more for files/folders in your home directory. The write protection gets re-enabled instantly after you remove it. That might be why the Rust-launched ctags can't work with the files in any of the subdirectories of the home folder (.rustup and AppData), but it's weird that I can still run ctags stand-alone, and create/edit files in the folders using other applications.

**Comment by DoumanAsh** [comment]
Yeah, having the same trouble.
Callstack, if you'd like to take a look:

```
> rusty-tags --verbose vi
Switching to single threaded for verbose output
Using configuration: vi_tags='rusty-tags.vi', emacs_tags='rusty-tags.emacs', ctags_exe='None', ctags_options=''
Found ctags executable: UniversalCtags("ctags")
Fetching source and metadata ...
Found package of (atty, 0.2.6) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\atty-0.2.6\src'
Found package of (synom, 0.11.3) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\synom-0.11.3\src'
Found package of (fnv, 1.0.6) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\fnv-1.0.6'
Found package of (winapi, 0.3.6) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\winapi-0.3.6\src'
Found package of (serde_json, 1.0.9) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\serde_json-1.0.9\src'
Found package of (lazy_static, 1.0.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\lazy_static-1.0.0\src'
Found package of (winapi, 0.2.8) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.8\src'
Found package of (termion, 1.5.1) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\termion-1.5.1\src'
Found package of (unicode-width, 0.1.4) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\unicode-width-0.1.4\src'
Found package of (textwrap, 0.10.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\textwrap-0.10.0\src'
Found package of (rand, 0.3.18) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\rand-0.3.18\src'
Found package of (strsim, 0.7.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\strsim-0.7.0\src'
Found package of (toml, 0.4.5) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\toml-0.4.5\src'
Found package of (streaming-iterator, 0.1.4) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\streaming-iterator-0.1.4\src'
Found package of (ansi_term, 0.11.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\ansi_term-0.11.0\src'
Found package of (serde_derive_internals, 0.19.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\serde_derive_internals-0.19.0\src'
Found package of (bitflags, 1.0.1) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\bitflags-1.0.1\src'
Found package of (syn, 0.11.11) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\syn-0.11.11\src'
Found package of (kernel32-sys, 0.2.2) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\kernel32-sys-0.2.2\src'
Found package of (num_cpus, 1.8.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\num_cpus-1.8.0\src'
Found package of (serde_derive, 1.0.27) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\serde_derive-1.0.27\src'
Found package of (semver, 0.9.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\semver-0.9.0\src'
Found package of (redox_termios, 0.1.1) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\redox_termios-0.1.1\src'
Found package of (unicode-xid, 0.0.4) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\unicode-xid-0.0.4\src'
Found package of (winapi-i686-pc-windows-gnu, 0.4.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\winapi-i686-pc-windows-gnu-0.4.0\src'
Found package of (rusty-tags, 3.0.0) with source at 'D:\repos\rust-code\rusty-tags\src'
Found package of (clap, 2.32.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\clap-2.32.0\src'
Found package of (dtoa, 0.4.2) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\dtoa-0.4.2\src'
Found package of (vec_map, 0.8.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\vec_map-0.8.0\src'
Found package of (winapi-x86_64-pc-windows-gnu, 0.4.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\winapi-x86_64-pc-windows-gnu-0.4.0\src'
Found package of (redox_syscall, 0.1.34) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\redox_syscall-0.1.34\src'
Found package of (num-traits, 0.1.41) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\num-traits-0.1.41\src'
Found package of (fuchsia-zircon-sys, 0.2.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\fuchsia-zircon-sys-0.2.0\src'
Found package of (fuchsia-zircon, 0.2.1) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\fuchsia-zircon-0.2.1\src'
Found package of (winapi-build, 0.1.1) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\winapi-build-0.1.1\src'
Found package of (tempfile, 2.2.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\tempfile-2.2.0\src'
Found package of (itoa, 0.3.4) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\itoa-0.3.4\src'
Found package of (libc, 0.2.33) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\libc-0.2.33\src'
Found package of (semver-parser, 0.7.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\semver-parser-0.7.0\src'
Found package of (bitflags, 0.7.0) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\bitflags-0.7.0\src'
Found package of (quote, 0.3.15) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\quote-0.3.15\src'
Found package of (serde, 1.0.27) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\serde-1.0.27\src'
Found package of (scoped_threadpool, 0.1.8) with source at 'D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\scoped_threadpool-0.1.8\src'
Found workspace members: [(rusty-tags, 3.0.0)]
Building tree for (winapi-x86_64-pc-windows-gnu, 0.4.0)
Building tree for (dtoa, 0.4.2)
Building tree for (winapi, 0.2.8)
Building tree for (semver-parser, 0.7.0)
Found dependencies of (termion, 1.5.1): [(libc, 0.2.33), (redox_syscall, 0.1.34), (redox_termios, 0.1.1)]
Building tree for (termion, 1.5.1)
Building tree for (redox_syscall, 0.1.34)
Found dependencies of (redox_termios, 0.1.1): [(redox_syscall, 0.1.34)]
Building tree for (redox_termios, 0.1.1)
Found dependencies of (fuchsia-zircon, 0.2.1): [(fuchsia-zircon-sys, 0.2.0)]
Building tree for (fuchsia-zircon, 0.2.1)
Found dependencies of (ansi_term, 0.11.0): [(winapi, 0.3.6)]
Building tree for (ansi_term, 0.11.0)
Building tree for (vec_map, 0.8.0)
Building tree for (strsim, 0.7.0)
Building tree for (unicode-xid, 0.0.4)
Found dependencies of (serde_json, 1.0.9): [(itoa, 0.3.4), (num-traits, 0.1.41), (serde, 1.0.27), (dtoa, 0.4.2)]
Building tree for (serde_json, 1.0.9)
Found dependencies of (tempfile, 2.2.0): [(rand, 0.3.18), (winapi, 0.2.8), (libc, 0.2.33), (kernel32-sys, 0.2.2), (redox_syscall, 0.1.34)]
Building tree for (tempfile, 2.2.0)
Found dependencies of (semver, 0.9.0): [(semver-parser, 0.7.0)]
Building tree for (semver, 0.9.0)
Building tree for (winapi-i686-pc-windows-gnu, 0.4.0)
Found dependencies of (num_cpus, 1.8.0): [(libc, 0.2.33)]
Building tree for (num_cpus, 1.8.0)
Building tree for (winapi-build, 0.1.1)
Building tree for (fnv, 1.0.6)
Building tree for (scoped_threadpool, 0.1.8)
Building tree for (bitflags, 0.7.0)
Found dependencies of (rand, 0.3.18): [(fuchsia-zircon, 0.2.1), (libc, 0.2.33)]
Building tree for (rand, 0.3.18)
Found dependencies of (toml, 0.4.5): [(serde, 1.0.27)]
Building tree for (toml, 0.4.5)
Found dependencies of (serde_derive_internals, 0.19.0): [(syn, 0.11.11), (synom, 0.11.3)]
Building tree for (serde_derive_internals, 0.19.0)
Building tree for (streaming-iterator, 0.1.4)
Building tree for (serde, 1.0.27)
Found dependencies of (atty, 0.2.6): [(termion, 1.5.1), (libc, 0.2.33), (winapi, 0.3.6)]
Building tree for (atty, 0.2.6)
Found dependencies of (serde_derive, 1.0.27): [(syn, 0.11.11), (quote, 0.3.15), (serde_derive_internals, 0.19.0)]
Building tree for (serde_derive, 1.0.27)
Found dependencies of (rusty-tags, 3.0.0): [(serde, 1.0.27), (streaming-iterator, 0.1.4), (serde_json, 1.0.9), (scoped_threadpool, 0.1.8), (tempfile, 2.2.0), (toml, 0.4.5), (fnv, 1.0.6), (serde_derive, 1.0.27),
(semver, 0.9.0), (clap, 2.32.0), (lazy_static, 1.0.0), (num_cpus, 1.8.0)]
Building tree for (rusty-tags, 3.0.0)
Found dependencies of (clap, 2.32.0): [(textwrap, 0.10.0), (unicode-width, 0.1.4), (strsim, 0.7.0), (vec_map, 0.8.0), (atty, 0.2.6), (bitflags, 1.0.1), (ansi_term, 0.11.0)]
Building tree for (clap, 2.32.0)
Found dependencies of (synom, 0.11.3): [(unicode-xid, 0.0.4)]
Building tree for (synom, 0.11.3)
Building tree for (num-traits, 0.1.41)
Building tree for (lazy_static, 1.0.0)
Building tree for (unicode-width, 0.1.4)
Building tree for (quote, 0.3.15)
Building tree for (itoa, 0.3.4)
Found dependencies of (syn, 0.11.11): [(quote, 0.3.15), (unicode-xid, 0.0.4), (synom, 0.11.3)]
Building tree for (syn, 0.11.11)
Found dependencies of (fuchsia-zircon-sys, 0.2.0): [(bitflags, 0.7.0)]
Building tree for (fuchsia-zircon-sys, 0.2.0)
Building tree for (libc, 0.2.33)
Found dependencies of (winapi, 0.3.6): [(winapi-x86_64-pc-windows-gnu, 0.4.0), (winapi-i686-pc-windows-gnu, 0.4.0)]
Building tree for (winapi, 0.3.6)
Found dependencies of (textwrap, 0.10.0): [(unicode-width, 0.1.4)]
Building tree for (textwrap, 0.10.0)
Building tree for (bitflags, 1.0.1)
Found dependencies of (kernel32-sys, 0.2.2): [(winapi, 0.2.8), (winapi-build, 0.1.1)]
Building tree for (kernel32-sys, 0.2.2)
Creating tags for: ["rusty-tags"] ...

Sources of depth=5
   Recreating tags for (bitflags, 0.7.0), because of missing cache file at '"C:\\Users\\Douman\\.rusty-tags\\cache\\bitflags-3834871892949103723.vi"'
   Recreating tags for (redox_syscall, 0.1.34), because of missing cache file at '"C:\\Users\\Douman\\.rusty-tags\\cache\\redox_syscall-278503860919345966.vi"'
   Recreating tags for (unicode-xid, 0.0.4), because of missing cache file at '"C:\\Users\\Douman\\.rusty-tags\\cache\\unicode-xid-2020714897146900772.vi"'

Creating tags ...
   for source:
      D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\bitflags-0.7.0\src

   cached at:
      C:\Users\Douman\AppData\Local\Temp\.tmpeSIPqP
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Message("ctags: cannot open tag file : Permission denied\r\n")', libcore\result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   4: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   5: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:475
   7: std::panicking::continue_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:390
   8: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:325
   9: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:77
  10: core::result::unwrap_failed<rusty_tags::rt_result::RtErr>
             at C:\projects\rust\src\libcore\macros.rs:26
  11: core::result::Result<(), rusty_tags::rt_result::RtErr>::unwrap<(),rusty_tags::rt_result::RtErr>
             at C:\projects\rust\src\libcore\result.rs:782
  12: rusty_tags::tags::update_tags::{{closure}}::{{closure}}
             at .\src\tags.rs:45
  13: scoped_threadpool::{{impl}}::call_box<closure>
             at D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\scoped_threadpool-0.1.8\src\lib.rs:71
  14: scoped_threadpool::{{impl}}::new::{{closure}}
             at D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\scoped_threadpool-0.1.8\src\lib.rs:127
thread 'main' panicked at 'Thread pool worker panicked', D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\scoped_threadpool-0.1.8\src\lib.rs:236:13
stack backtrace:
   0: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   1: std::sys::windows::backtrace::set_frames
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:104
   2: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   3: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   4: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   5: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   6: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:475
   7: std::panicking::begin_panic<str*>
             at C:\projects\rust\src\libstd\panicking.rs:409
   8: scoped_threadpool::Scope::join_all
             at D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\scoped_threadpool-0.1.8\src\lib.rs:236
   9: scoped_threadpool::{{impl}}::drop
             at D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\scoped_threadpool-0.1.8\src\lib.rs:248
  10: core::ptr::drop_in_place<scoped_threadpool::Scope>
             at C:\projects\rust\src\libcore\ptr.rs:59
  11: scoped_threadpool::Pool::scoped<closure,()>
             at D:\soft\Development\rustup\cargo_home\registry\src\github.com-1ecc6299db9ec823\scoped_threadpool-0.1.8\src\lib.rs:182
  12: rusty_tags::tags::update_tags
             at .\src\tags.rs:41
  13: rusty_tags::update_all_tags
             at .\src\main.rs:94
  14: rusty_tags::execute
             at .\src\main.rs:55
  15: rusty_tags::main
             at .\src\main.rs:47
  16: std::rt::lang_start::{{closure}}<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  17: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  18: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  19: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  20: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  21: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  22: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  23: std::rt::lang_start<()>
             at C:\projects\rust\src\libstd\rt.rs:74
  24: main
  25: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  26: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  27: BaseThreadInitThunk
  28: RtlUserThreadStart
```

**Comment by dan-t** [comment]
Hi,

can you run it with 'rusty-tags vi -f --verbose' and send me the output.

Greetings,
Daniel

**Comment by dan-t** [comment]
Could you please also run 'rusty-tags vi -f --verbose' with the current
github version.

**Comment by DoumanAsh** [comment]
Ok, here it [is](https://gist.github.com/DoumanAsh/a17f1e20332f83a99e395012b56ead87)
Current master branch

**Comment by dan-t** [comment]
Can you create the file 'C:\Users\Douman\AppData\Local\Temp\.tmpeTRn5x'?

If you can and you're calling 'rusty-tags' as the same user, then I've no clue why 'ctags'
executed from 'rusty-tags' shouldn't be able to create this file.

I don't use Windows for any kind of development and I also don't know what kind
of application specific file permission settings might be involved here.

So I can't do much more.

**Comment by DoumanAsh** [comment]
@dan-t there is a problem with that... it is always random and different name, there is no way to predict it. I'll try to debug it on weekend to see what could go wrong

**Comment by dan-t** [comment]
On Thu, Oct 25, 2018 at 08:47:29AM -0700, Douman wrote:
> @dan-t Yes I can, but it is not clear why rusty-tags fail... I'll try to debug
> more on weekend

Great!

The failing ctags executation should be in `src/tags.rs` line 145.

**Comment by dan-t** [comment]
With the current github version the verbose output will also contain the complete ctags command with all of its arguments, which might make it easier for debugging.

**Comment by DoumanAsh** [comment]
You'll be surprised... When I execute ctags by itself(using the same arguments) it works without errors....

**Comment by dan-t** [comment]
On Fri, Oct 26, 2018 at 09:03:49AM -0700, Douman wrote:
> You'll be surprised... When I execute ctags by itself(using the same arguments)
> it works without errors....

It seems to be some kind of application specific file permission handling.
I've no idea how and where these are set in Windows 10.

**Comment by DoumanAsh** [comment]
Just letting you know, I tried various ways to find out why permission is denied...
But I just have no idea so for now I give up.
Maybe someone more aware about Windows specific things could help

**Comment by dan-t** [comment]
On Sun, Nov 04, 2018 at 01:37:57AM -0800, Douman wrote:
> Just letting you know, I tried various ways to find out why permission is
> denied...
> But I just have no idea so for now I give up.
> Maybe someone more aware about Windows specific things could help

Thank you for trying!

**Comment by vipentti** [comment]
Hey!

I recently found this crate and thought to try it and ran into the same issue as discussed here before. I did some digging and and found that is related to `tempfile::NamedTempFile`.

Related issues in the tempfile crate:
*  https://github.com/Stebalien/tempfile/issues/66
*  https://github.com/Stebalien/tempfile/issues/69

It seems to have been fixed in https://github.com/Stebalien/tempfile/pull/76, so once that gets released the tempfile crate can be updated and this issue should be fixed.

As a temporary workaround, you can build this crate locally by updating the `tempfile` dependency in `Cargo.toml` to:
```
tempfile = { git = "https://github.com/Stebalien/tempfile", rev="95d08bd" }
```

Using this version, this crate now works on my W10 machine.

**NOTE:** I have not tested this crate with the updated tempfile crate on other OSses to make sure there are no breaking changes.
