### ISSUE TITLE
crash when trying to make ctags for fst

### ISSUE THREAD

**Issue by ethanpailes** [dan-t/rusty-tags#50]
I think this is due to rusty-tags getting into a state where it thinks that fst has a cyclic dependency on itself. The error seems to be coming from `src/tags.rs:237`.

Steps to Reproduce
===============

```
> git clone https://github.com/dan-t/rusty-tags.git
> cd rusty-tags && cargo build
> git clone https://github.com/BurntSushi/fst.git
> cd fst && ../rusty-tags/target/debug/rusty-tags vi
```

Output from some potentially interesting commands
=======================================

### Output of `RUST_BACKTRACE=1 ../rusty-tags/target/debug/rusty-tags vi`

```
Fetching source and metadata ...
Creating tags for: ["fst"] ...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Message("No such file or directory (os error 2)")', libcore/result.rs:1009:5
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Message("No such file or directory (os error 2)")', libcore/result.rs:1009:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at libcore/result.rs:808
  10: rusty_tags::tags::update_tags::{{closure}}::{{closure}}
             at src/tags.rs:69
  11: <F as scoped_threadpool::FnBox>::call_box
             at /home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.8/src/lib.rs:71
  12: scoped_threadpool::Pool::new::{{closure}}
             at /home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.8/src/lib.rs:127
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at libcore/result.rs:808
  10: rusty_tags::tags::update_tags::{{closure}}::{{closure}}
             at src/tags.rs:69
  11: <F as scoped_threadpool::FnBox>::call_box
             at /home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.8/src/lib.rs:71
  12: scoped_threadpool::Pool::new::{{closure}}
             at /home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.8/src/lib.rs:127
thread 'main' panicked at 'Thread pool worker panicked', /home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.8/src/lib.rs:236:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::begin_panic
             at libstd/panicking.rs:411
   6: scoped_threadpool::Scope::join_all
             at /home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.8/src/lib.rs:236
   7: <scoped_threadpool::Scope<'pool, 'scope> as core::ops::drop::Drop>::drop
             at /home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.8/src/lib.rs:248
   8: core::ptr::drop_in_place
             at libcore/ptr.rs:59
   9: scoped_threadpool::Pool::scoped
             at /home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.8/src/lib.rs:182
  10: rusty_tags::tags::update_tags
             at src/tags.rs:65
  11: rusty_tags::update_all_tags
             at src/main.rs:94
  12: rusty_tags::execute
             at src/main.rs:55
  13: rusty_tags::main
             at src/main.rs:47
  14: std::rt::lang_start::{{closure}}
             at libstd/rt.rs:74
  15: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  16: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  17: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  18: std::rt::lang_start
             at libstd/rt.rs:74
  19: main
  20: __libc_start_main
  21: _start
```

### Output of `../rusty-tags/target/debug/rusty-tags -v vi`

```
Switching to single threaded for verbose output
Using configuration: vi_tags='rusty-tags.vi', emacs_tags='rusty-tags.emacs', ctags_exe='None', ctags_options=''
Found ctags executable: ExuberantCtags("ctags")
Fetching source and metadata ...
Found package of (regex-syntax, 0.3.9) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/regex-syntax-0.3.9/src'
Found package of (quickcheck, 0.7.2) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/quickcheck-0.7.2/src'
Found package of (lazy_static, 0.2.11) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-0.2.11/src'
Found package of (rand_core, 0.3.0) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.3.0/src'
Found package of (fuchsia-zircon, 0.3.3) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/fuchsia-zircon-0.3.3/src'
Found package of (fst, 0.3.2) with source at '/home/ethan/repos/fst/src'
Found package of (cloudabi, 0.0.3) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/cloudabi-0.0.3'
Found package of (bitflags, 1.0.4) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/bitflags-1.0.4/src'
Found package of (rand, 0.5.5) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.5.5/src'
Found package of (libc, 0.2.43) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.43/src'
Found package of (winapi-i686-pc-windows-gnu, 0.4.0) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-i686-pc-windows-gnu-0.4.0/src'
Found package of (rand_core, 0.2.2) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/rand_core-0.2.2/src'
Found package of (winapi-x86_64-pc-windows-gnu, 0.4.0) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-x86_64-pc-windows-gnu-0.4.0/src'
Found package of (fnv, 1.0.6) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/fnv-1.0.6'
Found package of (fst-levenshtein, 0.2.1) with source at '/home/ethan/repos/fst/fst-levenshtein/src'
Found package of (utf8-ranges, 1.0.2) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/utf8-ranges-1.0.2/src'
Found package of (fst-regex, 0.2.1) with source at '/home/ethan/repos/fst/fst-regex/src'
Found package of (byteorder, 1.2.7) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/byteorder-1.2.7/src'
Found package of (winapi, 0.3.6) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/winapi-0.3.6/src'
Found package of (memmap, 0.6.2) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/memmap-0.6.2/src'
Found package of (fuchsia-zircon-sys, 0.3.3) with source at '/home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/fuchsia-zircon-sys-0.3.3/src'
Found workspace members: [(fst, 0.3.2)]
Building tree for (utf8-ranges, 1.0.2)
Building tree for (libc, 0.2.43)
Building tree for (fnv, 1.0.6)
Building tree for (byteorder, 1.2.7)
Building tree for (rand_core, 0.3.0)
Found dependencies of (rand_core, 0.2.2): [(rand_core, 0.3.0)]
Building tree for (rand_core, 0.2.2)
Building tree for (regex-syntax, 0.3.9)
Found dependencies of (memmap, 0.6.2): [(winapi, 0.3.6), (libc, 0.2.43)]
Building tree for (memmap, 0.6.2)
Building tree for (winapi-i686-pc-windows-gnu, 0.4.0)
Found dependencies of (winapi, 0.3.6): [(winapi-x86_64-pc-windows-gnu, 0.4.0), (winapi-i686-pc-windows-gnu, 0.4.0)]
Building tree for (winapi, 0.3.6)
Building tree for (fuchsia-zircon-sys, 0.3.3)
Found dependencies of (fst-regex, 0.2.1): [(utf8-ranges, 1.0.2), (fst, 0.3.2), (regex-syntax, 0.3.9)]
Building tree for (fst-regex, 0.2.1)
Building tree for (lazy_static, 0.2.11)
Found dependencies of (fuchsia-zircon, 0.3.3): [(fuchsia-zircon-sys, 0.3.3), (bitflags, 1.0.4)]
Building tree for (fuchsia-zircon, 0.3.3)
Found dependencies of (quickcheck, 0.7.2): [(rand_core, 0.2.2), (rand, 0.5.5)]
Building tree for (quickcheck, 0.7.2)
Found dependencies of (fst-levenshtein, 0.2.1): [(utf8-ranges, 1.0.2), (fst, 0.3.2)]
Building tree for (fst-levenshtein, 0.2.1)
Building tree for (winapi-x86_64-pc-windows-gnu, 0.4.0)
Found dependencies of (fst, 0.3.2): [(fst-regex, 0.2.1), (memmap, 0.6.2), (fnv, 1.0.6), (byteorder, 1.2.7), (quickcheck, 0.7.2), (rand, 0.5.5), (lazy_static, 0.2.11), (fst-levenshtein, 0.2.1)]
Building tree for (fst, 0.3.2)
Building tree for (bitflags, 1.0.4)
Found dependencies of (cloudabi, 0.0.3): [(bitflags, 1.0.4)]
Building tree for (cloudabi, 0.0.3)
Found dependencies of (rand, 0.5.5): [(libc, 0.2.43), (fuchsia-zircon, 0.3.3), (winapi, 0.3.6), (rand_core, 0.2.2), (cloudabi, 0.0.3)]
Building tree for (rand, 0.5.5)
Creating tags for: ["fst"] ...

Sources of depth=1
   Recreating tags for (fst-levenshtein, 0.2.1), because of missing tags file at '"/home/ethan/repos/fst/fst-levenshtein/rusty-tags.vi"'
   Recreating tags for (fst-regex, 0.2.1), because of missing tags file at '"/home/ethan/repos/fst/fst-regex/rusty-tags.vi"'

Creating tags ...
   with command: "ctags" "--recurse" "--languages=Rust" "--langdef=Rust" "--langmap=Rust:.rs" "--regex-Rust=/^[ \\t]*(#\\[[^\\]]\\][ \\t]*)*(pub[ \\t]+)?(extern[ \\t]+)?(\"[^\"]+\"[ \\t]+)?(unsafe[ \\t]+)?fn[ \\t]+([a-zA-Z0-9_]+)/\\6/f,functions,function definitions/" "--regex-Rust=/^[ \\t]*(pub[ \\t]+)?type[ \\t]+([a-zA-Z0-9_]+)/\\2/T,types,type definitions/" "--regex-Rust=/^[ \\t]*(pub[ \\t]+)?enum[ \\t]+([a-zA-Z0-9_]+)/\\2/g,enum,enumeration names/" "--regex-Rust=/^[ \\t]*(pub[ \\t]+)?struct[ \\t]+([a-zA-Z0-9_]+)/\\2/s,structure names/" "--regex-Rust=/^[ \\t]*(pub[ \\t]+)?mod[ \\t]+([a-zA-Z0-9_]+)\\s*\\{/\\2/m,modules,module names/" "--regex-Rust=/^[ \\t]*(pub[ \\t]+)?(static|const)[ \\t]+([a-zA-Z0-9_]+)/\\3/c,consts,static constants/" "--regex-Rust=/^[ \\t]*(pub[ \\t]+)?trait[ \\t]+([a-zA-Z0-9_]+)/\\2/t,traits,traits/" "--regex-Rust=/^[ \\t]*macro_rules![ \\t]+([a-zA-Z0-9_]+)/\\1/d,macros,macro definitions/" "-o" "/tmp/.tmp8gjdLR" "/home/ethan/repos/fst/fst-levenshtein/src"

   for source:
      /home/ethan/repos/fst/fst-levenshtein/src

   cached at:
      /tmp/.tmp8gjdLR

Copy tags ...
   from:
      /tmp/.tmp8gjdLR
   to:
      /home/ethan/.rusty-tags/cache/.tmprHo5gv

Move tags ...
   from:
      /home/ethan/.rusty-tags/cache/.tmprHo5gv
   to:
      /home/ethan/.rusty-tags/cache/fst-levenshtein-7207295818956455412.vi

Merging ...
   tags:
      /tmp/.tmp8gjdLR
      /home/ethan/.rusty-tags/cache/utf8-ranges-18205610573370416105.vi
      /home/ethan/.rusty-tags/cache/fst-5085178582101757549.vi

   into:
      /home/ethan/repos/fst/fst-levenshtein/src/.tmpb9RqVL
No such file or directory (os error 2)
```

**Comment by dan-t** [comment]
Thanks for the report!

The current github version should now have a fix for this.

**Comment by dan-t** [comment]
The previous fix has been more of a temporary workaround.

Now there should be a real fix for handling cyclic dependencies.

**Comment by ethanpailes** [comment]
Thanks! Awesome turnaround time!
