### ISSUE TITLE
rusty-tags.vi file not generated via rusty-tags vi command

### ISSUE THREAD

**Issue by duttaANI** [dan-t/rusty-tags#88]
I have universal tags installed with recurse flag. However, after executing `rusty-tags vi` command following error occurs -
```

❯ rusty-tags vi
Fetching source and metadata ...
Creating tags for: ockam, ockam_abac, ockam_core, ockam_macros, ockam_identity, ockam_channel, ockam_key_exchange_core, ockam_key_exchange_xx, ockam_node, ockam_executor, ockam_vault, ockam_key_exchange_x3dh, ockam_transport_tcp, ockam_transport_core, ockam_api, ockam_multiaddr, ockam_command, ockam_examples, ockam-ffi, ockam_transport_ble, ockam_transport_udp, ockam_transport_websocket, file_transfer, example_test_helper, hello_ockam, ockam_kafka, tcp_inlet_and_outlet, example_blocks ...
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Message("ctags: cannot open tag file : No such file or directory\n")', /home/aniruddha/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty-tags-3.10.0/src/tags.rs:76:thread '78<unnamed>
' panicked at 'note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
called `Result::unwrap()` on an `Err` value: Message("ctags: cannot open tag file : No such file or directory\n")', /home/aniruddha/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty-tags-3.10.0/src/tags.rs:76:78
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Message("ctags: cannot open tag file : No such file or directory\n")', /home/aniruddha/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty-tags-3.10.0/src/tags.rs:76:78
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Message("ctags: cannot open tag file : No such file or directory\n")', /home/aniruddha/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty-tags-3.10.0/src/tags.rs:76:78
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Message("ctags: cannot open tag file : No such file or directory\n")', /home/aniruddha/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty-tags-3.10.0/src/tags.rs:76:78
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Message("ctags: cannot open tag file : No such file or directory\n")', /home/aniruddha/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty-tags-3.10.0/src/tags.rs:76:78
thread 'main' panicked at 'Thread pool worker panicked', /home/aniruddha/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped_threadpool-0.1.9/src/lib.rs:236:13
❯ vim /home/aniruddha/.cargo/registry/src/github.com-1ecc6299db9ec823/rusty-tags-3.10.0/src/tags.rs
```

**Comment by duttaANI** [comment]
A workaround -

❯ cargo uninstall rusty-tags 
❯ sudo apt-get install rusty-tags 

Now the rusty-tags.vi files are getting generated

**Comment by dan-t** [comment]
Please call rusty-tags with the verbose option ´-v´ and show me the output.

Greetings,
Daniel
